### ISSUE TITLE
Last.fm Bio

### ISSUE THREAD

**Issue by 1-unknown-user** [19379/wsh_marc2003#1]
Last.fm Bio WSH Panel crash. if artist biography contains Unicode Character.

e.g.
http://www.last.fm/music/Franka+De+Mille/+wiki
http://www.last.fm/music/A%E1%B9%A3a

WSH Panel Mod (Last.fm Bio by marc2003): Parsing file "C:\Users\Steve\AppData\Roaming\foobar2000\wsh_marc2003\js\lodash.min.js"
WSH Panel Mod (Last.fm Bio by marc2003): Parsing file "C:\Users\Steve\AppData\Roaming\foobar2000\wsh_marc2003\js\helpers.js"
WSH Panel Mod (Last.fm Bio by marc2003): Parsing file "C:\Users\Steve\AppData\Roaming\foobar2000\wsh_marc2003\js\panel.js"
WSH Panel Mod (Last.fm Bio by marc2003): Parsing file "C:\Users\Steve\AppData\Roaming\foobar2000\wsh_marc2003\js\text.js"
Last.fm Bio: JSON.parse error:  
Error: WSH Panel Mod (Last.fm Bio by marc2003): Laufzeitfehler in Microsoft JScript:
Für die Eigenschaft "length" kann kein Wert abgerufen werden: Das Objekt ist Null oder undefiniert
File: C:\Users\Steve\AppData\Roaming\foobar2000\wsh_marc2003\js\text.js
Ln: 249, Col: 25
<source text only available at compile time>
WSH Panel Mod (Last.fm Bio by marc2003): initialized in 32 ms

**Comment by 19379** [comment]
both those artists work fine for me...

http://i.imgur.com/dTGHqQh.png

**Comment by 1-unknown-user** [comment]
Thanks for replying so quickly Marc,
after removing the cached files it works!

your scripts absolutely rock, thank you for all your contributions.
