### ISSUE TITLE
Last.fm User Charts

### ISSUE THREAD

**Issue by samithaj** [19379/wsh_marc2003#2]
WSH Panel Mod (Last.fm Artist Info/User Charts/Recommendations by marc2003): Microsoft JScript runtime error:
'@attr.rank' is null or not an object
File: C:\Users\sam\AppData\Roaming\foobar2000\wsh_marc2003\js\list.js
Line: 496, Col: 8
<source text only available at compile time>

**Comment by 19379** [comment]
assuming your last.fm username is samithaj, i just tested all 18 combinations that my script supports and every single one displays just fine. all i can suggest is browsing your foobar2000 profile folder\wsh_data\charts and removing all the json files and then reloading the script.

**Comment by samithaj** [comment]
I deleted the folder and deleted all internet explorer cache files too
Still got the issue though :/
Previously it worked fine , i think last.fm site changes caused this

**Comment by 19379** [comment]
so you're completely dismissing the fact i tested it thoroughly and think it's a problem at last.fm's end?? i even tested it just now and again, no errors. i will concede there is a layout issue because of some issue with the wrong playcounts being returned.

**Comment by samithaj** [comment]
I thought that would some regional issue,but seems like that's not the case it's working fine in a fresh install on columns and defaults UI
Sorry for not checking it first

**Comment by samithaj** [comment]
New version (v6.2) fixes this totally thank you marc!!

**Comment by 19379** [comment]
the empty results bug that was fixed in v6.1 should have caused the script to error before the part you reported so i didn't think it was related. oh well, so long as it's working now.
