### ISSUE TITLE
Echonest Review text 

### ISSUE THREAD

**Issue by smoralis** [19379/wsh_marc2003#4]
Sometimes the review script shows the text like the image below
![image](https://cloud.githubusercontent.com/assets/3080179/9627621/ebc2b082-516d-11e5-9156-f17dbbf8edc8.png)

**Comment by 19379** [comment]
Yes, I can reproduce that. Thanks for reporting. I'll update again when it's fixed.

**Comment by 19379** [comment]
This has now been fixed. To save you downloading the whole zip again, you can save this file directly inside the **wsh_marc2003\js** folder.

https://github.com/19379/wsh_marc2003/blob/master/js/list.js
