### ISSUE TITLE
m-tags titleformating

### ISSUE THREAD

**Issue by smoralis** [19379/wsh_marc2003#5]
When playing a m-tag  file that has a reference file to a http file , the titleformating doesn't return %artist%.

Suggest changing panel.js to

this.tf = function (t) {
			switch (true) {
			case !this.metadb:
				return "";
			case fb.IsPlaying && this.metadb.Path.indexOf("http") == 0:
				return _.tfe(t);
			
			case fb.IsPlaying && this.metadb.Path.split('.').pop() == "tags":
				return _.tfe(t);
				
			default:
				return _.tf(t, this.metadb);
			}
		}

**Comment by 19379** [comment]
https://github.com/19379/wsh_marc2003/wiki/Updates-&-Support

>I'm not taking feature requests and I'm not restoring any scripts or features missing from previous packages.

**Comment by smoralis** [comment]
OK.
Please update page "Changes from previous versions"
that m-tags are not fully supported.

**Comment by 19379** [comment]
Ah, bugger it. I'll restore this one thing as it's fairly minor...

**Comment by smoralis** [comment]
Thanks.
